import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import ClientProviders from "./ClientProviders";
import { ToastContainer } from "react-toastify";

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "e-Commerce",
  description: "Generated by alhasandhali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <ToastContainer position="top-right" autoClose={3000} />
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
